import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";
import { themes as prismThemes } from "prism-react-renderer";

// macOS EMFILE ("too many open files, watch") when `docs.path` is `../` (whole tome):
// - Webpack uses Watchpack → WATCHPACK_POLLING
// - @docusaurus/plugin-content-docs uses chokidar → CHOKIDAR_USEPOLLING
// `package.json` scripts also set these so the CLI sees them before any watcher starts.
// Opt out: WATCHPACK_POLLING=false / CHOKIDAR_USEPOLLING=false
if (!Object.hasOwn(process.env, "WATCHPACK_POLLING")) {
  process.env.WATCHPACK_POLLING = "true";
}
if (!Object.hasOwn(process.env, "CHOKIDAR_USEPOLLING")) {
  process.env.CHOKIDAR_USEPOLLING = "true";
}

const grimoireDevWatchPlugin = () => ({
  name: "grimoire-dev-watch",
  configureWebpack() {
    return {
      watchOptions: {
        ignored: [
          "**/.git/**",
          "**/node_modules/**",
          "**/.docusaurus/**",
          "**/build/**",
          "**/dist/**",
          "**/.turbo/**",
          "**/.next/**",
          "**/coverage/**",
        ],
      },
    };
  },
});

// Turn a raw slug (`concepts`, `ci-integration`) into a Sentence-case nav
// label (`Concepts`, `CI integration`) so the sidebar doesn't read like a
// `ls` listing. Well-known technical acronyms are upper-cased. Agent-authored
// `sidebar_label` / front-matter `title:` always wins over this fallback —
// this only fires for otherwise-raw slugs.
const SIDEBAR_ACRONYMS = new Set([
  "cli", "ci", "cd", "ai", "api", "sdk", "url", "uri", "http", "https",
  "json", "yaml", "md", "mdx", "sha", "dsl", "ide", "ui", "ux", "io",
  "pr", "mr", "os", "sql", "tls", "ssh", "cors", "dns", "tcp", "udp", "jwt",
]);
const humanizeSidebarLabel = (slug: string): string =>
  slug
    .split(/[-_\s]+/)
    .map((w, i) => {
      if (!w) return w;
      if (SIDEBAR_ACRONYMS.has(w.toLowerCase())) return w.toUpperCase();
      if (/^v\d/.test(w)) return w.toLowerCase();
      return i === 0 ? w.charAt(0).toUpperCase() + w.slice(1) : w;
    })
    .join(" ");

const SIDEBAR_WEIGHTS: Record<string, number> = {
  "index": -1000,
  "introduction": -900,
  "intro": -900,
  "getting-started": -800,
  "quickstart": -780,
  "quick-start": -780,
  "installation": -760,
  "install": -760,
  "tutorial": -700,
  "overview": -680,
  "concepts": -400,
  "guides": -300,
  "how-to": -280,
  "recipes": -260,
  "reference": 200,
  "api": 220,
  "cli": 220,
  "configuration": 230,
  "config": 230,
  "architecture": 600,
  "internals": 700,
  "development": 780,
  "contributing": 800,
  "roadmap": 880,
  "changelog": 900,
  "faq": 920,
  "troubleshooting": 940,
};
const sidebarWeight = (slug: string): number =>
  SIDEBAR_WEIGHTS[slug.toLowerCase()] ?? 0;

// Heuristic weights for common top-level slugs so the sidebar opens in a
// reading order a new visitor can actually follow — getting-started first,
// architecture / internals near the bottom, everything else alphabetical in
// between. Agent-authored `sidebar_position` always wins: this ordering is
// only consulted as a tie-breaker when front-matter position is the default
// (undefined), and only at the top level of the sidebar.
const config: Config = {
  title: "Grimoire",
  tagline: "Documentation generated by Grimoire",
  favicon: "img/logo.svg",
  url: "https://example.com",
  baseUrl: "/",
  organizationName: "grimoire",
  projectName: "docs",
  onBrokenLinks: "warn",
  markdown: {
    mermaid: true,
    format: "mdx",
  },
  presets: [
    [
      "classic",
      {
        docs: {
          path: "../",
          exclude: [
            "site/**",
            "**/node_modules/**",
            "**/.git/**",
            ".grimoire/**",
            "**/.grimoire/**",
            ".grimoire-seal",
            "**/.grimoire-seal",
            ".grimoire-progress.json",
            "**/.grimoire-progress.json",
            // `README.md` at the tome root is a GitHub-facing map of the
            // generated docs; `index.md` (slug: /) is the landing page.
            // If both are present Docusaurus tries to claim `/` twice and
            // emits a duplicate-route warning. Excluding README.md globally
            // keeps the GitHub README and the site landing page from
            // colliding, while `sidebarItemsGenerator` still hides any
            // nested README category indices from the sidebar.
            "**/README.md",
          ],
          routeBasePath: "/",
          sidebarPath: "./sidebars.ts",
          editLocalizedFiles: false,
          editUrl: undefined,
          // Autogenerated sidebar from the tome tree, with Grimoire-specific polish:
          //   - hide the landing page (`slug: /`) and `README` (duplicates the intro)
          //   - humanize raw slugs into Sentence-case labels
          //   - uppercase well-known acronyms (CLI, CI, API, …)
          //   - expand top-level categories by default — developer docs should
          //     reveal their table of contents, not hide it behind clicks
          // Agent-authored `sidebar_label` / `sidebar_position` front-matter
          // always wins over this fallback.
          sidebarItemsGenerator: async ({
            defaultSidebarItemsGenerator,
            ...args
          }) => {
            const items = await defaultSidebarItemsGenerator(args);
            const hiddenAnywhere = new Set(["README"]);
            const hiddenAtRoot = new Set(["index"]);
            const slugTail = (id: string): string => {
              const segs = id.split("/");
              return segs[segs.length - 1] ?? id;
            };
            const looksRawSlug = (s: string): boolean =>
              /^[a-z0-9]+([-_][a-z0-9]+)*$/.test(s);
            type Item = (typeof items)[number];
            const itemKey = (item: Item): string => {
              if (item.type === "doc") return slugTail(item.id).toLowerCase();
              if (item.type === "category") return item.label.toLowerCase();
              return "";
            };
            const sortTopLevel = (list: Item[]): Item[] =>
              [...list].sort((a, b) => {
                const ka = itemKey(a);
                const kb = itemKey(b);
                const wa = sidebarWeight(ka);
                const wb = sidebarWeight(kb);
                if (wa !== wb) return wa - wb;
                return ka.localeCompare(kb);
              });
            const walk = (item: Item, depth: number): Item | null => {
              if (item.type === "doc") {
                const tail = slugTail(item.id);
                if (hiddenAnywhere.has(tail)) return null;
                if (depth === 0 && hiddenAtRoot.has(tail)) return null;
                if (!item.label && looksRawSlug(tail)) {
                  return { ...item, label: humanizeSidebarLabel(tail) };
                }
                return item;
              }
              if (item.type === "category") {
                const label = looksRawSlug(item.label)
                  ? humanizeSidebarLabel(item.label)
                  : item.label;
                const children = item.items
                  .map((c: Item) => walk(c, depth + 1))
                  .filter((x: Item | null): x is Item => x !== null);
                return {
                  ...item,
                  label,
                  collapsed: depth === 0 ? false : item.collapsed,
                  items: children,
                };
              }
              return item;
            };
            return sortTopLevel(
              items
                .map((c: Item) => walk(c, 0))
                .filter((x: Item | null): x is Item => x !== null),
            );
          },
        },
        blog: false,
        theme: {
          customCss: "./src/css/custom.css",
        },
      } satisfies Preset.Options,
    ],
  ],
  plugins: [grimoireDevWatchPlugin],
  themes: ["@docusaurus/theme-mermaid"],
  themeConfig: {
    colorMode: {
      defaultMode: "light",
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: "Grimoire",
      logo: {
        alt: "Grimoire",
        src: "img/logo.svg",
        srcDark: "img/logo-dark.svg",
      },
      items: [
      ],
    },
    footer: {
      style: "dark",
      copyright: `© ${new Date().getFullYear()} ${"Grimoire"}`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
    mermaid: { theme: { light: "neutral", dark: "dark" } },
  },
};

export default config;
